# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import consul_pb2 as consul__pb2


class ConsulStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.unary_unary(
        '/Consul/SayHello',
        request_serializer=consul__pb2.HelloRequest.SerializeToString,
        response_deserializer=consul__pb2.HelloReply.FromString,
        )
    self.Notify = channel.unary_unary(
        '/Consul/Notify',
        request_serializer=consul__pb2.NotifyRequest.SerializeToString,
        response_deserializer=consul__pb2.NotifyReply.FromString,
        )


class ConsulServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SayHello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Notify(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ConsulServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=consul__pb2.HelloRequest.FromString,
          response_serializer=consul__pb2.HelloReply.SerializeToString,
      ),
      'Notify': grpc.unary_unary_rpc_method_handler(
          servicer.Notify,
          request_deserializer=consul__pb2.NotifyRequest.FromString,
          response_serializer=consul__pb2.NotifyReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Consul', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
